export const VALIDATION_MESSAGE_TYPE = {
  EXCEPTION_OCCURED: 'Exception occurred',
  UNAUTHORIZED: 'Unauthorized',
  AUTHENTICATION_FAILED: 'Authentication Failed',
};

export enum ERROR_MESSAGE_CODE {
  BAD_REQUEST = '10001',
  INTERNAL_SERVER_ERROR = '10002',
  UNAUTHORIZED = '10003',
  USERNAME_EMAIL_MISMATCH = '10100',
  INVALID_RESET_PASSWORD_LINK = '10101',
  ONBOARDING_REQUEST_ALREADY_EXISTS = '10110',
  DELETE_ONBOARDING_REQUEST_FAILED = '10111',
  COMPANY_CREATION_FAILED = '10120',
  COMPANY_NAME_ALREADY_EXISTS = '10121',
  GST_NUMBER_ALREADY_EXISTS = '10122',
  BUSINESS_UNIT_CREATION_FAILED = '10200',
  BUSINESS_UNIT_NAME_ALREADY_EXISTS = '10201',
  DIVISION_CREATION_FAILED = '10210',
  DIVISION_NAME_ALREADY_EXISTS = '10211',
  DEPARTMENT_CREATION_FAILED = '10220',
  DEPARTMENT_NAME_ALREADY_EXISTS = '10221',
  LEVEL_CREATION_FAILED = '10230',
  LEVEL_NAME_ALREADY_EXISTS = '10231',
  DESIGNATION_CREATION_FAILED = '10240',
  DESIGNATION_NAME_ALREADY_EXISTS = '10241',
  ASSIGNMENT_NAME_EXISTS = '10250',
  ACTIVE_ASSIGNMENT_EXISTS = '10251',
  EMPLOYEE_CREATION_FAILED = '10300',
  EMPLOYEE_USERNAME_ALREADY_EXISTS = '10301',
  EMPLOYEE_EMAIL_ALREADY_EXISTS = '10302',
  NEW_EMPLOYEE_RESET_PASSWORD_EMAIL_FAILED = '10303',

  FIRM_NAME_EXISTS = '10401',
  FIRM_EMPLOYEE_EXISTS = '10402',

  QUESTION_DELETION_FAILED = '10403'
}

export const ERROR_MESSAGES_COMMON = {
  BAD_REQUEST: {
    code: ERROR_MESSAGE_CODE.BAD_REQUEST,
    description: 'Bad Request',
  },
  INTERNAL_SERVER_ERROR: {
    code: ERROR_MESSAGE_CODE.INTERNAL_SERVER_ERROR,
    description: 'Internal Server Error. Please contact administrator.',
  },
  UNAUTHORIZED: {
    code: ERROR_MESSAGE_CODE.UNAUTHORIZED,
    description: 'Unauthorized',
  },
};

export const ERROR_MESSAGES_ASSIGNMENTS = {
  ASSIGNMENT_NAME_EXISTS: {
    code: ERROR_MESSAGE_CODE.ASSIGNMENT_NAME_EXISTS,
    description: 'Assignment Name already exists',
  },
  ACTIVE_ASSIGNMENT_EXISTS: {
    code: ERROR_MESSAGE_CODE.ACTIVE_ASSIGNMENT_EXISTS,
    description: 'This assignment is already started',
  },
};

export const ERROR_MESSAGES_EXTERNAL_FIRMS = {
  FIRM_NAME_EXISTS: {
    code: ERROR_MESSAGE_CODE.FIRM_NAME_EXISTS,
    description: 'Firm already registered',
  },
  FIRM_EMPLOYEE_EXISTS: {
    code: ERROR_MESSAGE_CODE.FIRM_EMPLOYEE_EXISTS,
    description: 'Firm employee already exists',
  },
};

export const ICC_TEAM_MAXIMUM_TENURE_YEARS = 3;
